export const THEMES = [
    {
      name: "light",
      label: "Light",
      colors: ["#ffffff", "#5a67d8", "#8b5cf6", "#1a202c"],
    },
    {
      name: "dark",
      label: "Dark",
      colors: ["#1f2937", "#8b5cf6", "#ec4899", "#1a202c"],
    },
    {
      name: "cupcake",
      label: "Cupcake",
      colors: ["#f5f5f4", "#65c3c8", "#ef9fbc", "#291334"],
    },
    {
      name: "forest",
      label: "Forest",
      colors: ["#1f1d1d", "#3ebc96", "#70c217", "#e2e8f0"],
    },
    {
      name: "bumblebee",
      label: "Bumblebee",
      colors: ["#ffffff", "#f8e36f", "#f0d50c", "#1c1917"],
    },
    {
      name: "emerald",
      label: "Emerald",
      colors: ["#ffffff", "#66cc8a", "#3b82f6", "#1e3a8a"],
    },
    {
      name: "corporate",
      label: "Corporate",
      colors: ["#ffffff", "#4b6bfb", "#7b92b2", "#1d232a"],
    },
    {
      name: "synthwave",
      label: "Synthwave",
      colors: ["#2d1b69", "#e779c1", "#58c7f3", "#f8f8f2"],
    },
    {
      name: "retro",
      label: "Retro",
      colors: ["#e4d8b4", "#ea6962", "#6aaa64", "#282425"],
    },
    {
      name: "cyberpunk",
      label: "Cyberpunk",
      colors: ["#ffee00", "#ff7598", "#75d1f0", "#1a103d"],
    },
    {
      name: "valentine",
      label: "Valentine",
      colors: ["#f0d6e8", "#e96d7b", "#a991f7", "#37243c"],
    },
    {
      name: "halloween",
      label: "Halloween",
      colors: ["#0d0d0d", "#ff7800", "#006400", "#ffffff"],
    },
    {
      name: "garden",
      label: "Garden",
      colors: ["#e9e7e7", "#ec4899", "#16a34a", "#374151"],
    },
  
    {
      name: "aqua",
      label: "Aqua",
      colors: ["#193549", "#4cd4e3", "#9059ff", "#f8d766"],
    },
    {
      name: "lofi",
      label: "Lofi",
      colors: ["#0f0f0f", "#1a1919", "#232323", "#2c2c2c"],
    },
    {
      name: "pastel",
      label: "Pastel",
      colors: ["#f7f3f5", "#d1c1d7", "#a1e3d8", "#4a98f1"],
    },
    {
      name: "fantasy",
      label: "Fantasy",
      colors: ["#ffe7d6", "#a21caf", "#3b82f6", "#f59e0b"],
    },
    {
      name: "wireframe",
      label: "Wireframe",
      colors: ["#e6e6e6", "#b3b3b3", "#b3b3b3", "#888888"],
    },
    {
      name: "black",
      label: "Black",
      colors: ["#000000", "#191919", "#313131", "#4a4a4a"],
    },
    {
      name: "luxury",
      label: "Luxury",
      colors: ["#171618", "#1e293b", "#94589c", "#d4a85a"],
    },
    {
      name: "dracula",
      label: "Dracula",
      colors: ["#282a36", "#ff79c6", "#bd93f9", "#f8f8f2"],
    },
    {
      name: "cmyk",
      label: "CMYK",
      colors: ["#f0f0f0", "#0891b2", "#ec4899", "#facc15"],
    },
    {
      name: "autumn",
      label: "Autumn",
      colors: ["#f2f2f2", "#8c1f11", "#f28c18", "#6f4930"],
    },
    {
      name: "business",
      label: "Business",
      colors: ["#f5f5f5", "#1e40af", "#3b82f6", "#f97316"],
    },
    {
      name: "acid",
      label: "Acid",
      colors: ["#110e0e", "#ff00f2", "#ff7a00", "#99ff01"],
    },
    {
      name: "lemonade",
      label: "Lemonade",
      colors: ["#ffffff", "#67e8f9", "#f5d742", "#2c3333"],
    },
    {
      name: "night",
      label: "Night",
      colors: ["#0f172a", "#38bdf8", "#818cf8", "#e2e8f0"],
    },
    {
      name: "coffee",
      label: "Coffee",
      colors: ["#20161f", "#dd9866", "#497174", "#eeeeee"],
    },
    {
      name: "winter",
      label: "Winter",
      colors: ["#ffffff", "#0284c7", "#d946ef", "#0f172a"],
    },
    {
      name: "dim",
      label: "Dim",
      colors: ["#1c1c27", "#10b981", "#ff5a5f", "#0f172a"],
    },
    {
      name: "nord",
      label: "Nord",
      colors: ["#eceff4", "#5e81ac", "#81a1c1", "#3b4252"],
    },
    {
      name: "sunset",
      label: "Sunset",
      colors: ["#1e293b", "#f5734c", "#ec4899", "#ffffff"],
    },
  ];
  
  export const LANGUAGES = [
    "English",
    "Spanish",
    "French",
    "German",
    "Mandarin",
    "Japanese",
    "Korean",
    "Hindi",
    "Russian",
    "Portuguese",
    "Arabic",
    "Italian",
    "Turkish",
    "Dutch",
    "Nepali"
  ];

  export const COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];
  
  
  export const LANGUAGE_TO_FLAG = {
    afghanistan: "af",
    albania: "al",
    algeria: "dz",
    andorra: "ad",
    angola: "ao",
    argentina: "ar",
    armenia: "am",
    australia: "au",
    austria: "at",
    azerbaijan: "az",
    bahamas: "bs",
    bahrain: "bh",
    bangladesh: "bd",
    barbados: "bb",
    belarus: "by",
    belgium: "be",
    belize: "bz",
    benin: "bj",
    bhutan: "bt",
    bolivia: "bo",
    bosnia_and_herzegovina: "ba",
    botswana: "bw",
    brazil: "br",
    brunei: "bn",
    bulgaria: "bg",
    burkina_faso: "bf",
    burundi: "bi",
    cambodia: "kh",
    cameroon: "cm",
    canada: "ca",
    cape_verde: "cv",
    central_african_republic: "cf",
    chad: "td",
    chile: "cl",
    china: "cn",
    colombia: "co",
    comoros: "km",
    costa_rica: "cr",
    croatia: "hr",
    cuba: "cu",
    cyprus: "cy",
    czech_republic: "cz",
    denmark: "dk",
    djibouti: "dj",
    dominica: "dm",
    dominican_republic: "do",
    dr_congo: "cd",
    ecuador: "ec",
    egypt: "eg",
    el_salvador: "sv",
    equatorial_guinea: "gq",
    eritrea: "er",
    estonia: "ee",
    eswatini: "sz",
    ethiopia: "et",
    fiji: "fj",
    finland: "fi",
    france: "fr",
    gabon: "ga",
    gambia: "gm",
    georgia: "ge",
    germany: "de",
    ghana: "gh",
    greece: "gr",
    grenada: "gd",
    guatemala: "gt",
    guinea: "gn",
    guinea_bissau: "gw",
    guyana: "gy",
    haiti: "ht",
    honduras: "hn",
    hungary: "hu",
    iceland: "is",
    india: "in",
    indonesia: "id",
    iran: "ir",
    iraq: "iq",
    ireland: "ie",
    israel: "il",
    italy: "it",
    ivory_coast: "ci",
    jamaica: "jm",
    japan: "jp",
    jordan: "jo",
    kazakhstan: "kz",
    kenya: "ke",
    kiribati: "ki",
    korea_north: "kp",
    korea_south: "kr",
    kuwait: "kw",
    kyrgyzstan: "kg",
    laos: "la",
    latvia: "lv",
    lebanon: "lb",
    lesotho: "ls",
    liberia: "lr",
    libya: "ly",
    liechtenstein: "li",
    lithuania: "lt",
    luxembourg: "lu",
    madagascar: "mg",
    malawi: "mw",
    malaysia: "my",
    maldives: "mv",
    mali: "ml",
    malta: "mt",
    marshall_islands: "mh",
    mauritania: "mr",
    mauritius: "mu",
    mexico: "mx",
    micronesia: "fm",
    moldova: "md",
    monaco: "mc",
    mongolia: "mn",
    montenegro: "me",
    morocco: "ma",
    mozambique: "mz",
    myanmar: "mm",
    namibia: "na",
    nauru: "nr",
    nepal: "np",
    netherlands: "nl",
    new_zealand: "nz",
    nicaragua: "ni",
    niger: "ne",
    nigeria: "ng",
    north_macedonia: "mk",
    norway: "no",
    oman: "om",
    pakistan: "pk",
    palau: "pw",
    palestine: "ps",
    panama: "pa",
    papua_new_guinea: "pg",
    paraguay: "py",
    peru: "pe",
    philippines: "ph",
    poland: "pl",
    portugal: "pt",
    qatar: "qa",
    romania: "ro",
    russia: "ru",
    rwanda: "rw",
    saint_kitts_and_nevis: "kn",
    saint_lucia: "lc",
    saint_vincent_and_the_grenadines: "vc",
    samoa: "ws",
    san_marino: "sm",
    sao_tome_and_principe: "st",
    saudi_arabia: "sa",
    senegal: "sn",
    serbia: "rs",
    seychelles: "sc",
    sierra_leone: "sl",
    singapore: "sg",
    slovakia: "sk",
    slovenia: "si",
    solomon_islands: "sb",
    somalia: "so",
    south_africa: "za",
    south_sudan: "ss",
    spain: "es",
    sri_lanka: "lk",
    sudan: "sd",
    suriname: "sr",
    sweden: "se",
    switzerland: "ch",
    syria: "sy",
    taiwan: "tw",
    tajikistan: "tj",
    tanzania: "tz",
    thailand: "th",
    timor_leste: "tl",
    togo: "tg",
    tonga: "to",
    trinidad_and_tobago: "tt",
    tunisia: "tn",
    turkey: "tr",
    turkmenistan: "tm",
    tuvalu: "tv",
    uganda: "ug",
    ukraine: "ua",
    united_arab_emirates: "ae",
    united_kingdom: "gb",
    united_states: "us",
    uruguay: "uy",
    uzbekistan: "uz",
    vanuatu: "vu",
    venezuela: "ve",
    vietnam: "vn",
    yemen: "ye",
    zambia: "zm",
    zimbabwe: "zw"
  };
  

 